# Site settings
baseURL = "https://tianshihao.github.io/"
title = "笔记本子"
author = "Shihao Tian"
copyright = "Copyright © 2025"
languageCode = "cn"
DefaultContentLanguage = "zh-cn"
disqusShortname = ""
googleAnalytics = "UA-1234567890" # or "G-xxxxxxxx" for Google Analytics v4
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
hasCJKLanguage = true
theme = "hugo-theme-tokiwa"

[markup]
  [markup.highlight]
    style = "monokailight"  # Syntax highlighting theme, e.g., monokailight, solarized-light, dracula, etc.

  [markup.tableOfContents] # Correct spelling
    startLevel = 1
    endLevel = 4

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
description = "Tokiwa-iro is the theme color of this site."
math = true                 # Enable KaTeX for math rendering
env = "production"          # Set the environment, often used for conditional settings like analytics
useChineseFonts = true      # Use Chinese fonts like Noto Serif
bannerFont = "fonts/exampleFont" # Custom font for the title
postDateFormat = "2006-1-2" # Date format for posts
fuse = true                 # Fuse.js enabled for searchbox

[menu]
  [[menu.main]]
    name = "Posts"
    identifier = "posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    name = "Series"
    url = "/series/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params.social]
  github = "http://github.com/tianshihao"
  # instagram = "http://example.com/"
  # bilibili = "http://example.com/"
  # weibo = "http://example.com/"
  # zhihu = "http://example.com/"
  # twitter = "http://twitter.com/"
  # gitlab = "http://gitlab.com/"
  # youtube = "http://youtube.com/"

[outputs]
  home = ["HTML", "RSS", "JSON"]
